baseURL = 'https://nasman.dev/'
languageCode = 'en-us'
title = 'nasman.dev'
theme = 'PaperMod'

[params]
description = "Notes on code and security"
author = "nasman.dev"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[params.homeInfoParams]
Title = "nasman.dev"
Content = "Notes on code and security"

[[params.socialIcons]]
name = "github"
url = "https://github.com/nasmandev"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/jonas-n√§sman-26082b1a"

[[params.socialIcons]]
name = "x"
url = "https://x.com/nasmandev"

[menu]
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 15

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true